version: '3.6'
services:
  cedar-java:
    container_name: cedar-java
    image: "metadatacenter/cedar-java:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-java
    networks:
      - cedarnet
  cedar-microservice:
    depends_on:
        - cedar-java
    container_name: cedar-microservice
    image: "metadatacenter/cedar-microservice:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-microservice
    networks:
      - cedarnet
    volumes:
      - cedar_ca:/cedar/ca
  schema-server:
    depends_on:
        - cedar-microservice
    container_name: schema-server
    image: "metadatacenter/cedar-schema-server:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-schema-server
    networks:
      - cedarnet
    ports:
      - "${CEDAR_SCHEMA_HTTP_PORT}:9003"
      - "${CEDAR_SCHEMA_ADMIN_PORT}:9103"
      - "${CEDAR_SCHEMA_STOP_PORT}:9203"
    volumes:
      - schema_log:/cedar/log/cedar-schema-server/
      - cedar_ca:/cedar/ca
    environment:
      - CEDAR_HOST
      - CEDAR_NET_GATEWAY
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD
      - CEDAR_MONGO_HOST
      - CEDAR_MONGO_PORT
      - CEDAR_NEO4J_HOST
      - CEDAR_NEO4J_REST_PORT
      - CEDAR_NEO4J_BOLT_PORT
      - CEDAR_NEO4J_USER_NAME
      - CEDAR_NEO4J_USER_PASSWORD
      - CEDAR_REDIS_PERSISTENT_HOST
      - CEDAR_REDIS_PERSISTENT_PORT
  user-server:
    depends_on:
        - cedar-microservice
    container_name: user-server
    image: "metadatacenter/cedar-user-server:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-user-server
    networks:
      - cedarnet
    ports:
      - "${CEDAR_USER_HTTP_PORT}:9005"
      - "${CEDAR_USER_ADMIN_PORT}:9105"
      - "${CEDAR_USER_STOP_PORT}:9205"
    volumes:
      - user_log:/cedar/log/cedar-user-server/
      - cedar_ca:/cedar/ca
    environment:
      - CEDAR_HOST
      - CEDAR_NET_GATEWAY
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD
      - CEDAR_MONGO_HOST
      - CEDAR_MONGO_PORT
      - CEDAR_NEO4J_HOST
      - CEDAR_NEO4J_REST_PORT
      - CEDAR_NEO4J_BOLT_PORT
      - CEDAR_NEO4J_USER_NAME
      - CEDAR_NEO4J_USER_PASSWORD
      - CEDAR_KEYCLOAK_HOST
      - CEDAR_KEYCLOAK_HTTP_PORT
      - CEDAR_REDIS_PERSISTENT_HOST
      - CEDAR_REDIS_PERSISTENT_PORT
      - CEDAR_ADMIN_USER_PASSWORD
  submission-server:
    depends_on:
        - cedar-microservice
    container_name: submission-server
    image: "metadatacenter/cedar-submission-server:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-submission-server
    networks:
      - cedarnet
    ports:
      - "${CEDAR_SUBMISSION_HTTP_PORT}:9010"
      - "${CEDAR_SUBMISSION_ADMIN_PORT}:9110"
      - "${CEDAR_SUBMISSION_STOP_PORT}:9210"
    volumes:
      - submission_log:/cedar/log/cedar-submission-server/
      - cedar_ca:/cedar/ca
    environment:
      - CEDAR_HOST
      - CEDAR_NET_GATEWAY
      - CEDAR_MICROSERVICE_HOST
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD
      - CEDAR_MONGO_HOST
      - CEDAR_MONGO_PORT
      - CEDAR_KEYCLOAK_HOST
      - CEDAR_KEYCLOAK_HTTP_PORT
      - CEDAR_NEO4J_HOST
      - CEDAR_NEO4J_REST_PORT
      - CEDAR_NEO4J_BOLT_PORT
      - CEDAR_NEO4J_USER_NAME
      - CEDAR_NEO4J_USER_PASSWORD
      - CEDAR_NCBI_SRA_FTP_HOST
      - CEDAR_NCBI_SRA_FTP_USER
      - CEDAR_NCBI_SRA_FTP_PASSWORD
      - CEDAR_NCBI_SRA_FTP_DIRECTORY
      - CEDAR_IMMPORT_SUBMISSION_USER
      - CEDAR_IMMPORT_SUBMISSION_PASSWORD
      - CEDAR_ADMIN_USER_API_KEY
      - CEDAR_REDIS_PERSISTENT_HOST
      - CEDAR_REDIS_PERSISTENT_PORT
      - CEDAR_MESSAGING_ADMIN_PORT
      - CEDAR_MESSAGING_HTTP_PORT
  group-server:
    depends_on:
        - cedar-microservice
    container_name: group-server
    image: "metadatacenter/cedar-group-server:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-group-server
    networks:
      - cedarnet
    ports:
      - "${CEDAR_GROUP_HTTP_PORT}:9009"
      - "${CEDAR_GROUP_ADMIN_PORT}:9109"
      - "${CEDAR_GROUP_STOP_PORT}:9209"
    volumes:
      - group_log:/cedar/log/cedar-group-server/
      - cedar_ca:/cedar/ca
    environment:
      - CEDAR_HOST
      - CEDAR_NET_GATEWAY
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD
      - CEDAR_MONGO_HOST
      - CEDAR_MONGO_PORT
      - CEDAR_NEO4J_HOST
      - CEDAR_NEO4J_REST_PORT
      - CEDAR_NEO4J_BOLT_PORT
      - CEDAR_NEO4J_USER_NAME
      - CEDAR_NEO4J_USER_PASSWORD
      - CEDAR_REDIS_PERSISTENT_HOST
      - CEDAR_REDIS_PERSISTENT_PORT
      - CEDAR_KEYCLOAK_HOST
      - CEDAR_KEYCLOAK_HTTP_PORT
  artifact-server:
    depends_on:
        - cedar-microservice
    container_name: artifact-server
    image: "metadatacenter/cedar-artifact-server:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-artifact-server
    networks:
      - cedarnet
    ports:
      - "${CEDAR_ARTIFACT_HTTP_PORT}:9001"
      - "${CEDAR_ARTIFACT_ADMIN_PORT}:9101"
      - "${CEDAR_ARTIFACT_STOP_PORT}:9201"
    volumes:
      - artifact_log:/cedar/log/cedar-artifact-server/
      - cedar_ca:/cedar/ca
    environment:
      - CEDAR_HOST
      - CEDAR_NET_GATEWAY
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD
      - CEDAR_MONGO_HOST
      - CEDAR_MONGO_PORT
      - CEDAR_NEO4J_HOST
      - CEDAR_NEO4J_REST_PORT
      - CEDAR_NEO4J_BOLT_PORT
      - CEDAR_NEO4J_USER_NAME
      - CEDAR_NEO4J_USER_PASSWORD
      - CEDAR_KEYCLOAK_HOST
      - CEDAR_KEYCLOAK_HTTP_PORT
      - CEDAR_REDIS_PERSISTENT_HOST
      - CEDAR_REDIS_PERSISTENT_PORT
      - CEDAR_TEST_USER1_ID
      - CEDAR_VALIDATION_ENABLED
  worker-server:
    depends_on:
        - cedar-microservice
    container_name: worker-server
    image: "metadatacenter/cedar-worker-server:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-worker-server
    networks:
      - cedarnet
    ports:
      - "${CEDAR_WORKER_HTTP_PORT}:9011"
      - "${CEDAR_WORKER_ADMIN_PORT}:9111"
      - "${CEDAR_WORKER_STOP_PORT}:9211"
    volumes:
      - worker_log:/cedar/log/cedar-worker-server/
      - cedar_ca:/cedar/ca
    environment:
      - CEDAR_HOST
      - CEDAR_NET_GATEWAY
      - CEDAR_MICROSERVICE_HOST
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD
      - CEDAR_MONGO_HOST
      - CEDAR_MONGO_PORT
      - CEDAR_MYSQL_ROOT_PASSWORD
      - CEDAR_LOG_MYSQL_HOST
      - CEDAR_LOG_MYSQL_PORT
      - CEDAR_LOG_MYSQL_DB
      - CEDAR_LOG_MYSQL_USER
      - CEDAR_LOG_MYSQL_PASSWORD
      - CEDAR_MESSAGING_MYSQL_HOST
      - CEDAR_MESSAGING_MYSQL_PORT
      - CEDAR_MESSAGING_MYSQL_DB
      - CEDAR_MESSAGING_MYSQL_USER
      - CEDAR_MESSAGING_MYSQL_PASSWORD
      - CEDAR_KEYCLOAK_HOST
      - CEDAR_KEYCLOAK_HTTP_PORT
      - CEDAR_ADMIN_USER_API_KEY
      - CEDAR_NEO4J_HOST
      - CEDAR_NEO4J_REST_PORT
      - CEDAR_NEO4J_BOLT_PORT
      - CEDAR_NEO4J_USER_NAME
      - CEDAR_NEO4J_USER_PASSWORD
      - CEDAR_REDIS_PERSISTENT_HOST
      - CEDAR_REDIS_PERSISTENT_PORT
      - CEDAR_ELASTICSEARCH_HOST
      - CEDAR_ELASTICSEARCH_REST_PORT
      - CEDAR_ELASTICSEARCH_TRANSPORT_PORT
      - CEDAR_SUBMISSION_TEMPLATE_ID_1
      - CEDAR_SUBMISSION_TEMPLATE_ID_2
      - CEDAR_VALUERECOMMENDER_HTTP_PORT
      - CEDAR_RESOURCE_ADMIN_PORT
      - CEDAR_TRUSTED_FOLDERS
  valuerecommender-server:
    depends_on:
        - cedar-microservice
    container_name: valuerecommender-server
    image: "metadatacenter/cedar-valuerecommender-server:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-valuerecommender-server
    networks:
      - cedarnet
    ports:
      - "${CEDAR_VALUERECOMMENDER_HTTP_PORT}:9006"
      - "${CEDAR_VALUERECOMMENDER_ADMIN_PORT}:9106"
      - "${CEDAR_VALUERECOMMENDER_STOP_PORT}:9206"
    volumes:
      - valuerecommender_log:/cedar/log/cedar-valuerecommender-server/
      - cedar_ca:/cedar/ca
    environment:
      - CEDAR_HOST
      - CEDAR_NET_GATEWAY
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD
      - CEDAR_MONGO_HOST
      - CEDAR_MONGO_PORT
      - CEDAR_NEO4J_HOST
      - CEDAR_NEO4J_REST_PORT
      - CEDAR_NEO4J_BOLT_PORT
      - CEDAR_NEO4J_USER_NAME
      - CEDAR_NEO4J_USER_PASSWORD
      - CEDAR_KEYCLOAK_HOST
      - CEDAR_KEYCLOAK_HTTP_PORT
      - CEDAR_ELASTICSEARCH_HOST
      - CEDAR_ELASTICSEARCH_REST_PORT
      - CEDAR_ELASTICSEARCH_TRANSPORT_PORT
      - CEDAR_REDIS_PERSISTENT_HOST
      - CEDAR_REDIS_PERSISTENT_PORT
  terminology-server:
    depends_on:
        - cedar-microservice
    container_name: terminology-server
    image: "metadatacenter/cedar-terminology-server:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-terminology-server
    networks:
      - cedarnet
    ports:
      - "${CEDAR_TERMINOLOGY_HTTP_PORT}:9004"
      - "${CEDAR_TERMINOLOGY_ADMIN_PORT}:9104"
      - "${CEDAR_TERMINOLOGY_STOP_PORT}:9204"
    volumes:
      - terminology_log:/cedar/log/cedar-terminology-server/
      - terminology_data:/cedar/cache/terminology/
      - cedar_ca:/cedar/ca
    environment:
      - CEDAR_HOST
      - CEDAR_NET_GATEWAY
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD
      - CEDAR_MONGO_HOST
      - CEDAR_MONGO_PORT
      - CEDAR_NEO4J_HOST
      - CEDAR_NEO4J_REST_PORT
      - CEDAR_NEO4J_BOLT_PORT
      - CEDAR_NEO4J_USER_NAME
      - CEDAR_NEO4J_USER_PASSWORD
      - CEDAR_REDIS_PERSISTENT_HOST
      - CEDAR_REDIS_PERSISTENT_PORT
      - CEDAR_KEYCLOAK_HOST
      - CEDAR_KEYCLOAK_HTTP_PORT
      - CEDAR_BIOPORTAL_API_KEY
      - CEDAR_BIOPORTAL_REST_BASE
      - CEDAR_TEST_USER1_ID
  repo-server:
    depends_on:
        - cedar-microservice
    container_name: repo-server
    image: "metadatacenter/cedar-repo-server:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-repo-server
    networks:
      - cedarnet
    ports:
      - "${CEDAR_REPO_HTTP_PORT}:9002"
      - "${CEDAR_REPO_ADMIN_PORT}:9102"
      - "${CEDAR_REPO_STOP_PORT}:9202"
    volumes:
      - repo_log:/cedar/log/cedar-repo-server/
      - cedar_ca:/cedar/ca
    environment:
      - CEDAR_HOST
      - CEDAR_NET_GATEWAY
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD
      - CEDAR_MONGO_HOST
      - CEDAR_MONGO_PORT
      - CEDAR_NEO4J_HOST
      - CEDAR_NEO4J_REST_PORT
      - CEDAR_NEO4J_BOLT_PORT
      - CEDAR_NEO4J_USER_NAME
      - CEDAR_NEO4J_USER_PASSWORD
      - CEDAR_REDIS_PERSISTENT_HOST
      - CEDAR_REDIS_PERSISTENT_PORT
      - CEDAR_KEYCLOAK_HOST
      - CEDAR_KEYCLOAK_HTTP_PORT
  resource-server:
    depends_on:
        - cedar-microservice
    container_name: resource-server
    image: "metadatacenter/cedar-resource-server:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-resource-server
    networks:
      - cedarnet
    ports:
      - "${CEDAR_RESOURCE_HTTP_PORT}:9007"
      - "${CEDAR_RESOURCE_ADMIN_PORT}:9107"
      - "${CEDAR_RESOURCE_STOP_PORT}:9207"
    volumes:
      - resource_log:/cedar/log/cedar-resource-server/
      - resource_state:/state
      - cedar_ca:/cedar/ca
    environment:
      - CEDAR_HOST
      - CEDAR_NET_GATEWAY
      - CEDAR_MICROSERVICE_HOST
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD
      - CEDAR_MONGO_HOST
      - CEDAR_MONGO_PORT
      - CEDAR_KEYCLOAK_HOST
      - CEDAR_KEYCLOAK_HTTP_PORT
      - CEDAR_ADMIN_USER_API_KEY
      - CEDAR_ADMIN_USER_PASSWORD
      - CEDAR_CADSR_ADMIN_USER_API_KEY
      - CEDAR_NEO4J_HOST
      - CEDAR_NEO4J_REST_PORT
      - CEDAR_NEO4J_BOLT_PORT
      - CEDAR_NEO4J_USER_NAME
      - CEDAR_NEO4J_USER_PASSWORD
      - CEDAR_SALT_API_KEY
      - CEDAR_ELASTICSEARCH_HOST
      - CEDAR_ELASTICSEARCH_REST_PORT
      - CEDAR_ELASTICSEARCH_TRANSPORT_PORT
      - CEDAR_REDIS_PERSISTENT_HOST
      - CEDAR_REDIS_PERSISTENT_PORT
      - CEDAR_VALIDATION_ENABLED
      - CEDAR_SUBMISSION_TEMPLATE_ID_1
      - CEDAR_SUBMISSION_TEMPLATE_ID_2
      - CEDAR_ARTIFACT_HTTP_PORT
      - CEDAR_ARTIFACT_ADMIN_PORT
      - CEDAR_CADSR_ONTOLOGIES_FOLDER
      - CEDAR_TRUSTED_FOLDERS
    extra_hosts:
      - "auth.${CEDAR_HOST}:${CEDAR_NET_GATEWAY}"
  messaging-server:
    depends_on:
        - cedar-microservice
    container_name: messaging-server
    image: "metadatacenter/cedar-messaging-server:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-messaging-server
    networks:
      - cedarnet
    ports:
      - "${CEDAR_MESSAGING_HTTP_PORT}:9012"
      - "${CEDAR_MESSAGING_ADMIN_PORT}:9112"
      - "${CEDAR_MESSAGING_STOP_PORT}:9212"
    volumes:
      - messaging_log:/cedar/log/cedar-messaging-server/
      - cedar_ca:/cedar/ca
    environment:
      - CEDAR_HOST
      - CEDAR_NET_GATEWAY
      - CEDAR_ADMIN_USER_API_KEY
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD
      - CEDAR_KEYCLOAK_HOST
      - CEDAR_KEYCLOAK_HTTP_PORT
      - CEDAR_MONGO_HOST
      - CEDAR_MONGO_PORT
      - CEDAR_NEO4J_HOST
      - CEDAR_NEO4J_REST_PORT
      - CEDAR_NEO4J_BOLT_PORT
      - CEDAR_NEO4J_USER_NAME
      - CEDAR_NEO4J_USER_PASSWORD
      - CEDAR_MYSQL_ROOT_PASSWORD
      - CEDAR_MESSAGING_MYSQL_HOST
      - CEDAR_MESSAGING_MYSQL_PORT
      - CEDAR_MESSAGING_MYSQL_DB
      - CEDAR_MESSAGING_MYSQL_USER
      - CEDAR_MESSAGING_MYSQL_PASSWORD
      - CEDAR_REDIS_PERSISTENT_HOST
      - CEDAR_REDIS_PERSISTENT_PORT
      - CEDAR_TEST_USER1_ID
      - CEDAR_TEST_USER2_ID
  openview-server:
    depends_on:
      - cedar-microservice
    container_name: openview-server
    image: "metadatacenter/cedar-openview-server:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-openview-server
    networks:
      - cedarnet
    ports:
      - "${CEDAR_OPENVIEW_HTTP_PORT}:9013"
      - "${CEDAR_OPENVIEW_ADMIN_PORT}:9113"
      - "${CEDAR_OPENVIEW_STOP_PORT}:9213"
    volumes:
      - openview_log:/cedar/log/cedar-openview-server/
      - cedar_ca:/cedar/ca
    environment:
      - CEDAR_HOST
      - CEDAR_NET_GATEWAY
      - CEDAR_MICROSERVICE_HOST
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD
      - CEDAR_MONGO_HOST
      - CEDAR_MONGO_PORT
      - CEDAR_NEO4J_HOST
      - CEDAR_NEO4J_REST_PORT
      - CEDAR_NEO4J_BOLT_PORT
      - CEDAR_NEO4J_USER_NAME
      - CEDAR_NEO4J_USER_PASSWORD
      - CEDAR_REDIS_PERSISTENT_HOST
      - CEDAR_REDIS_PERSISTENT_PORT
      - CEDAR_ARTIFACT_HTTP_PORT
      - CEDAR_ARTIFACT_ADMIN_PORT
  internals-server:
    depends_on:
      - cedar-microservice
    container_name: internals-server
    image: "metadatacenter/cedar-internals-server:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-internals-server
    networks:
      - cedarnet
    ports:
      - "${CEDAR_INTERNALS_HTTP_PORT}:9014"
      - "${CEDAR_INTERNALS_ADMIN_PORT}:9114"
      - "${CEDAR_INTERNALS_STOP_PORT}:9214"
    volumes:
      - internals_log:/cedar/log/cedar-internals-server/
      - cedar_ca:/cedar/ca
    environment:
      - CEDAR_HOST
      - CEDAR_NET_GATEWAY
      - CEDAR_MICROSERVICE_HOST
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD
      - CEDAR_MONGO_HOST
      - CEDAR_MONGO_PORT
      - CEDAR_KEYCLOAK_HOST
      - CEDAR_KEYCLOAK_HTTP_PORT
      - CEDAR_ADMIN_USER_API_KEY
      - CEDAR_NEO4J_HOST
      - CEDAR_NEO4J_REST_PORT
      - CEDAR_NEO4J_BOLT_PORT
      - CEDAR_NEO4J_USER_NAME
      - CEDAR_NEO4J_USER_PASSWORD
      - CEDAR_SALT_API_KEY
      - CEDAR_ELASTICSEARCH_HOST
      - CEDAR_ELASTICSEARCH_REST_PORT
      - CEDAR_ELASTICSEARCH_TRANSPORT_PORT
      - CEDAR_REDIS_PERSISTENT_HOST
      - CEDAR_REDIS_PERSISTENT_PORT
      - CEDAR_ADMIN_USER_PASSWORD
      - CEDAR_LOG_MYSQL_HOST
      - CEDAR_LOG_MYSQL_PORT
      - CEDAR_LOG_MYSQL_DB
      - CEDAR_LOG_MYSQL_USER
      - CEDAR_LOG_MYSQL_PASSWORD
      - CEDAR_CADSR_ADMIN_USER_API_KEY
  impex-server:
    depends_on:
      - cedar-microservice
    container_name: impex-server
    image: "metadatacenter/cedar-impex-server:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-impex-server
    networks:
      - cedarnet
    ports:
      - "${CEDAR_IMPEX_HTTP_PORT}:9008"
      - "${CEDAR_IMPEX_ADMIN_PORT}:9108"
      - "${CEDAR_IMPEX_STOP_PORT}:9208"
    volumes:
      - impex_log:/cedar/log/cedar-impex-server/
      - cedar_ca:/cedar/ca
    environment:
      - CEDAR_HOST
      - CEDAR_NET_GATEWAY
      - CEDAR_MICROSERVICE_HOST
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD
      - CEDAR_MONGO_HOST
      - CEDAR_MONGO_PORT
      - CEDAR_KEYCLOAK_HOST
      - CEDAR_KEYCLOAK_HTTP_PORT
      - CEDAR_ADMIN_USER_API_KEY
      - CEDAR_NEO4J_HOST
      - CEDAR_NEO4J_REST_PORT
      - CEDAR_NEO4J_BOLT_PORT
      - CEDAR_NEO4J_USER_NAME
      - CEDAR_NEO4J_USER_PASSWORD
      - CEDAR_SALT_API_KEY
      - CEDAR_ELASTICSEARCH_HOST
      - CEDAR_ELASTICSEARCH_REST_PORT
      - CEDAR_ELASTICSEARCH_TRANSPORT_PORT
      - CEDAR_REDIS_PERSISTENT_HOST
      - CEDAR_REDIS_PERSISTENT_PORT
      - CEDAR_ADMIN_USER_PASSWORD
      - CEDAR_LOG_MYSQL_HOST
      - CEDAR_LOG_MYSQL_PORT
      - CEDAR_LOG_MYSQL_DB
      - CEDAR_LOG_MYSQL_USER
      - CEDAR_LOG_MYSQL_PASSWORD
      - CEDAR_CADSR_ADMIN_USER_API_KEY

networks:
  cedarnet:
    external:
      name: cedarnet

volumes:
  cedar_ca:
    name: cedar_ca
  openview_log:
    name: openview_log
  group_log:
    name: group_log
  messaging_log:
    name: messaging_log
  repo_log:
    name: repo_log
  resource_log:
    name: resource_log
  resource_state:
    name: resource_state
  schema_log:
    name: schema_log
  submission_log:
    name: submission_log
  artifact_log:
    name: artifact_log
  terminology_data:
    name: terminology_data
  terminology_log:
    name: terminology_log
  user_log:
    name: user_log
  valuerecommender_log:
    name: valuerecommender_log
  worker_log:
    name: worker_log
  internals_log:
    name: internals_log
  impex_log:
    name: impex_log
