version: '3.6'
services:
  mysql:
    container_name: mysql
    image: "metadatacenter/cedar-mysql:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-mysql
    networks:
      - cedarnet
    ports:
      - ${CEDAR_KEYCLOAK_MYSQL_PORT}:3306
    volumes:
      - mysql_log:/var/log/mysql
      - mysql_data:/var/lib/mysql
    environment:
      - CEDAR_MYSQL_ROOT_PASSWORD
      - CEDAR_NET_GATEWAY

  mongo:
    container_name: mongo
    image: "metadatacenter/cedar-mongo:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-mongo
    networks:
      - cedarnet
    ports:
      - "${CEDAR_MONGO_PORT}:27017"
    volumes:
      - mongo_log:/data/log
      - mongo_data:/data/db
      - mongo_state:/data/state
    environment:
      - CEDAR_MONGO_ROOT_USER_NAME
      - CEDAR_MONGO_ROOT_USER_PASSWORD
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD

  redis-persistent:
    container_name: redis-persistent
    image: "metadatacenter/cedar-redis-persistent:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-redis-persistent
    networks:
      - cedarnet
    ports:
      - ${CEDAR_REDIS_PERSISTENT_PORT}:6379
    volumes:
      - redis_log:/log
      - redis_data:/data
    sysctls:
      - net.core.somaxconn=512

  elasticsearch:
    container_name: elasticsearch
    image: "metadatacenter/cedar-elasticsearch:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-elasticsearch
    networks:
      - cedarnet
    ports:
      - ${CEDAR_ELASTICSEARCH_REST_PORT}:9200
      - ${CEDAR_ELASTICSEARCH_TRANSPORT_PORT}:9300
    volumes:
      - elasticsearch_log:/usr/share/elasticsearch/logs
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"

  neo4j:
    container_name: neo4j
    image: "metadatacenter/cedar-neo4j:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-neo4j
    networks:
      - cedarnet
    ports:
      - ${CEDAR_NEO4J_REST_PORT}:7474
      - ${CEDAR_NEO4J_BOLT_PORT}:7687
    volumes:
      - neo4j_log:/logs
      - neo4j_data:/data
      - neo4j_state:/state
    environment:
      - CEDAR_NEO4J_USER_NAME
      - CEDAR_NEO4J_USER_PASSWORD
      - CEDAR_HOST
      - CEDAR_ADMIN_USER_API_KEY

  keycloak:
    container_name: keycloak
    image: "metadatacenter/cedar-keycloak:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-keycloak
    networks:
      - cedarnet
    ports:
      - ${CEDAR_KEYCLOAK_HTTP_PORT}:8080
      - ${CEDAR_KEYCLOAK_HTTPS_PORT}:8443
    volumes:
      - keycloak_log:/opt/jboss/keycloak/standalone/log
    environment:
      - CEDAR_MYSQL_ROOT_PASSWORD
      - CEDAR_KEYCLOAK_MYSQL_USER
      - CEDAR_KEYCLOAK_MYSQL_PASSWORD
      - CEDAR_KEYCLOAK_MYSQL_PORT
      - CEDAR_KEYCLOAK_MYSQL_HOST
      - CEDAR_KEYCLOAK_MYSQL_DB
      - CEDAR_KEYCLOAK_ADMIN_USER
      - CEDAR_KEYCLOAK_ADMIN_PASSWORD
      - CEDAR_ADMIN_USER_API_KEY
      - CEDAR_HOST
      - CEDAR_NET_GATEWAY
      - CEDAR_RESOURCE_HTTP_PORT

  nginx:
    container_name: nginx
    image: "metadatacenter/cedar-nginx:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-nginx
    networks:
      - cedarnet
    ports:
      - ${CEDAR_NGINX_HTTP_PORT}:80
      - ${CEDAR_NGINX_HTTPS_PORT}:443
    volumes:
      - nginx_log:/etc/nginx/log
      - cedar_cert:/usr/local/etc/certificates
    environment:
      - CEDAR_HOST
      - CEDAR_MICROSERVICE_HOST
      - CEDAR_KEYCLOAK_HOST
      - CEDAR_FRONTEND_HOST

networks:
  cedarnet:
    external:
      name: cedarnet

volumes:
  neo4j_log:
    name: neo4j_log
  neo4j_data:
    name: neo4j_data
  neo4j_state:
    name: neo4j_state
  elasticsearch_log:
    name: elasticsearch_log
  elasticsearch_data:
    name: elasticsearch_data
  redis_log:
    name: redis_log
  redis_data:
    name: redis_data
  mongo_log:
    name: mongo_log
  mongo_data:
    name: mongo_data
  mongo_state:
    name: mongo_state
  mysql_log:
    name: mysql_log
  mysql_data:
    name: mysql_data
  keycloak_log:
    name: keycloak_log
  nginx_log:
    name: nginx_log
  cedar_cert:
    name: cedar_cert
